<?php
/**
 * Relationship Cloning
 *
 * @package Native_Content_Relationships
 * @since 1.4.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class NATICORE_Cloning
 *
 * Clone posts and all their relationships.
 */
class NATICORE_Cloning {

	/**
	 * Constructor
	 */
	public function __construct() {
		add_action( 'admin_post_ncr_clone_post', array( $this, 'handle_clone' ) );
	}

	/**
	 * Clone a post and all its relationships
	 *
	 * @param int    $source_id Source post ID.
	 * @param array  $args      Optional arguments.
	 * @return int|WP_Error New post ID or error.
	 */
	public static function clone_post( $source_id, $args = array() ) {
		$source = get_post( $source_id );
		if ( ! $source ) {
			return new WP_Error( 'invalid_post', __( 'Source post not found.', 'native-content-relationships' ) );
		}

		$defaults = array(
			'title'         => sprintf(
				/* translators: %s: Original post title */
				__( '%s (Copy)', 'native-content-relationships' ),
				$source->post_title
			),
			'status'        => 'draft',
			'copy_date'     => false,
			'copy_author'   => true,
			'copy_meta'     => true,
			'copy_tax'      => true,
			'copy_relations' => true,
		);

		$args = wp_parse_args( $args, $defaults );

		// Create new post
		$new_post_data = array(
			'post_title'   => $args['title'],
			'post_content' => $source->post_content,
			'post_excerpt' => $source->post_excerpt,
			'post_status'  => $args['status'],
			'post_type'    => $source->post_type,
			'post_author'  => $args['copy_author'] ? $source->post_author : get_current_user_id(),
		);

		if ( $args['copy_date'] ) {
			$new_post_data['post_date']     = $source->post_date;
			$new_post_data['post_date_gmt'] = $source->post_date_gmt;
		}

		$new_id = wp_insert_post( $new_post_data, true );

		if ( is_wp_error( $new_id ) ) {
			return $new_id;
		}

		// Copy post meta
		if ( $args['copy_meta'] ) {
			$meta = get_post_meta( $source_id );
			foreach ( $meta as $key => $values ) {
				// Skip relationship internal meta
				if ( strpos( $key, '_ncr_' ) === 0 || strpos( $key, '_naticore_' ) === 0 ) {
					continue;
				}
				foreach ( $values as $value ) {
					add_post_meta( $new_id, $key, $value );
				}
			}
		}

		// Copy taxonomies
		if ( $args['copy_tax'] ) {
			$taxonomies = get_object_taxonomies( $source->post_type, 'objects' );
			foreach ( $taxonomies as $taxonomy ) {
				$terms = wp_get_post_terms( $source_id, $taxonomy->name, array( 'fields' => 'ids' ) );
				if ( ! is_wp_error( $terms ) && ! empty( $terms ) ) {
					wp_set_post_terms( $new_id, $terms, $taxonomy->name );
				}
			}
		}

		// Clone relationships
		if ( $args['copy_relations'] ) {
			self::clone_relationships( $source_id, $new_id );
		}

		/**
		 * Action after cloning a post.
		 *
		 * @param int   $new_id    New post ID.
		 * @param int   $source_id Source post ID.
		 * @param array $args      Clone arguments.
		 */
		do_action( 'ncr_post_cloned', $new_id, $source_id, $args );

		return $new_id;
	}

	/**
	 * Clone relationships from source to target
	 *
	 * @param int $source_id Source post ID.
	 * @param int $target_id Target post ID.
	 * @return int Number of relationships cloned.
	 */
	public static function clone_relationships( $source_id, $target_id ) {
		$relations = NATICORE_API::get_all_relations( $source_id );
		$count     = 0;

		foreach ( $relations as $rel ) {
			// Skip if the related post is the source itself
			if ( $rel->to_id == $source_id ) {
				continue;
			}

			$result = NATICORE_API::add_relation(
				$target_id,
				$rel->to_id,
				$rel->type,
				isset( $rel->direction ) ? $rel->direction : null
			);

			if ( ! is_wp_error( $result ) ) {
				$count++;

				// Copy metadata
				if ( class_exists( 'NATICORE_Meta_API' ) ) {
					$meta = NATICORE_Meta_API::get_all_meta( $rel->id );
					if ( ! empty( $meta ) ) {
						$new_rel_id = $result;
						foreach ( $meta as $key => $value ) {
							// Skip internal meta
							if ( strpos( $key, '_' ) === 0 ) {
								continue;
							}
							NATICORE_Meta_API::update_meta( $new_rel_id, $key, $value );
						}
					}
				}
			}
		}

		return $count;
	}

	/**
	 * Handle clone via admin POST
	 */
	public function handle_clone() {
		if ( ! current_user_can( 'edit_posts' ) ) {
			wp_die( esc_html__( 'You do not have permission to perform this action.', 'native-content-relationships' ) );
		}

		$source_id = absint( $_POST['source_id'] ?? 0 );

		if ( ! $source_id ) {
			wp_die( esc_html__( 'Invalid source post.', 'native-content-relationships' ) );
		}

		// Verify nonce generated by add_clone_action().
		check_admin_referer( 'ncr_clone_' . $source_id );

		$title = sanitize_text_field( wp_unslash( $_POST['title'] ?? '' ) );

		$args = array();
		if ( $title ) {
			$args['title'] = $title;
		}

		$result = self::clone_post( $source_id, $args );

		if ( is_wp_error( $result ) ) {
			wp_die( esc_html( $result->get_error_message() ) );
		}

		wp_safe_redirect( get_edit_post_link( $result, 'raw' ) );
		exit;
	}

	/**
	 * Add clone button to post row actions
	 *
	 * @param array    $actions Post actions.
	 * @param WP_Post  $post    Post object.
	 * @return array Modified actions.
	 */
	public static function add_clone_action( $actions, $post ) {
		if ( current_user_can( 'edit_posts' ) && NATICORE_API::get_all_relations( $post->ID ) ) {
			$clone_url = wp_nonce_url(
				admin_url( 'admin-post.php?action=ncr_clone_post&source_id=' . $post->ID ),
				'ncr_clone_' . $post->ID
			);
			$actions['ncr_clone'] = '<a href="' . esc_url( $clone_url ) . '" title="'
				. esc_attr__( 'Clone with relationships', 'native-content-relationships' ) . '">'
				. esc_html__( 'Clone + Relations', 'native-content-relationships' ) . '</a>';
		}
		return $actions;
	}
}
